# Generated by Django 4.1.7 on 2023-02-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="description",
            new_name="caption",
        ),
    ]
