# Generated by Django 4.1.7 on 2023-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_description_post_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
